#!/usr/bin/env python
# from pymatgen.electronic_structure.dos import CompleteDos
from pymatgen.electronic_structure.core import Spin
from pymatgen.electronic_structure.plotter import DosPlotter
from pymatgen.electronic_structure.core import Spin, Orbital
from pymatgen.io.vasp.outputs import Vasprun, Procar
from pymatgen.core.ion import Ion
import sys
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
vasprun = Vasprun(sys.argv[1])

pdos = vasprun.pdos
tdos = vasprun.tdos
idos = vasprun.idos
efermi = vasprun.efermi
energy = vasprun.eigenvalues
structure = vasprun.structures


de = tdos.energies[1] - tdos.energies[0]
diff = []
total = tdos.densities[Spin.up]
diffx = tdos.energies-efermi+de/2
for i in range(len(idos.densities[Spin.up])-1):
    diff.append((total[i+1] - total[i])/de)

plt.plot(tdos.energies-efermi,tdos.densities[Spin.up])
plt.plot(tdos.energies-efermi,idos.densities[Spin.up])
plt.plot(diffx[0:-1],np.array(diff)/1000)
plt.show()
