#!/usr/bin/env python

import sys,json,subprocess,os
potcorr = json.load(open(os.path.join(os.path.dirname(__file__),'../ML/data/eatom.json')))

poscar = open(os.path.join(sys.argv[1],'POSCAR'),'r')
lines = poscar.readlines()

species = list(filter(None,subprocess.Popen('grep TITEL POTCAR | awk \'{print $4}\'',stdout=subprocess.PIPE,shell=True).communicate()[0].decode().split('\n')))
numberofatoms = lines[6][:-1].lstrip()
numberofatoms = " ".join(numberofatoms.split())
natoms = numberofatoms.split(' ')
numberofatoms = sum(map(int, natoms))

corr = 0
for i in range(len(natoms)):
    if species[i] in potcorr.keys():
        corr += float(potcorr[species[i]])*float(natoms[i])
    else:
        print('0')
        exit()
corr /= numberofatoms


print(corr)
