#!/usr/bin/env python

import subprocess

#from tables import *
from sys import argv

import argparse

parser = argparse.ArgumentParser(description='Generate POTCAR.')
parser.add_argument('els', nargs='*')
parser.add_argument('-s','--set',default='zintl')
args = parser.parse_args()


#Be and Mg and Bi differ with MP, transition metals not checked


if args.set == 'zintl':
    potentials = {'H':'','He':'','Li':'_sv', 'Be':'', 'B':'', 'C':'', 'N':'', 'O':'', 'F':'', 'Ne':'', 'Na':'_pv', 'Mg':'',
              'Al':'', 'Si':'', 'P':'', 'S':'', 'Cl':'', 'Ar':'', 'K':'_sv', 'Ca':'_sv', 'Sc':'_sv', 'Ti':'_sv', 'V':'_sv',
              'Cr':'_pv', 'Mn':'_pv', 'Fe':'', 'Co':'', 'Ni':'', 'Cu':'', 'Zn':'', 'Ga':'_d', 'Ge':'_d', 'As':'', 'Se':'',
              'Br':'', 'Kr':'', 'Rb':'_sv', 'Sr':'_sv', 'Y':'_sv', 'Zr':'_sv', 'Nb':'_sv', 'Mo':'_sv', 'Tc':'_pv', 'Ru':'_pv',
              'Rh':'_pv', 'Pd':'', 'Ag':'', 'Cd':'', 'In':'_d', 'Sn':'_d', 'Sb':'', 'Te':'', 'I':'', 'Xe':'', 'Cs':'_sv',
              'Ba':'_sv', 'Lu':'_3', 'Hf':'_pv', 'Ta':'_pv', 'W':'_pv', 'Re':'', 'Os':'', 'Ir':'', 'Pt':'', 'Au':'',
              'Hg':'', 'Tl':'_d', 'Pb':'_d', 'Bi':'_d', 'Po':'_d', 'At':'_d','Rn':'', 'La' : '',
              'Ce' : '', 'Pr' : '_3', 'Nd' : '_3', 'Pm' : '_3', 'Sm' : '_3', 'Eu' : '_2', 'Gd' : '_3','Tb' : '_3', 'Dy' : '_3' , 'Ho' : '_3', 'Er' : '_3', 'Tm' : '_3','Yb' : '_2',
              'Ac' : '', 'Th' : '', 'Pa' : '', 'U' : '', 'Np' : '', 'Pu' : '', 'Am' : '', 'Cm' : '', 'Bk' : '?' ,  'Ra' : '_sv', 'Fr' : '_sv'}
    potdir = '$VSC_DATA_VO/POTCAR_PBE/'
elif args.set == 'mp':
    potentials = {'H':'','He':'','Li':'_sv', 'Be':'_sv', 'B':'', 'C':'', 'N':'', 'O':'', 'F':'', 'Ne':'', 'Na':'_pv', 'Mg':'_pv',
              'Al':'', 'Si':'', 'P':'', 'S':'', 'Cl':'', 'Ar':'', 'K':'_sv', 'Ca':'_sv', 'Sc':'_sv', 'Ti':'_pv', 'V':'_sv',
              'Cr':'_pv', 'Mn':'_pv', 'Fe':'', 'Co':'', 'Ni':'', 'Cu':'', 'Zn':'', 'Ga':'_d', 'Ge':'_d', 'As':'', 'Se':'',
              'Br':'', 'Kr':'', 'Rb':'_sv', 'Sr':'_sv', 'Y':'_sv', 'Zr':'_sv', 'Nb':'_sv', 'Mo':'_sv', 'Tc':'_pv', 'Ru':'_pv',
              'Rh':'_pv', 'Pd':'', 'Ag':'', 'Cd':'', 'In':'_d', 'Sn':'_d', 'Sb':'', 'Te':'', 'I':'', 'Xe':'', 'Cs':'_sv',
              'Ba':'_sv', 'Lu':'_3', 'Hf':'_pv', 'Ta':'_pv', 'W':'_pv', 'Re':'', 'Os':'', 'Ir':'', 'Pt':'', 'Au':'',
              'Hg':'', 'Tl':'_d', 'Pb':'_d', 'Bi':'', 'Po':'_d', 'At':'_d','Rn':'', 'La' : '', 'Lu' : '_3',
              'Ce' : '', 'Pr' : '_3', 'Nd' : '_3', 'Pm' : '_3', 'Sm' : '_3', 'Eu' : '', 'Gd' : '','Tb' : '_3', 'Dy' : '_3' , 'Ho' : '_3', 'Er' : '_3', 'Tm' : '_3','Yb' : '',
               'Ac' : '', 'Th' : '', 'Pa' : '', 'U' : '', 'Np' : '', 'Pu' : '', 'Am' : '', 'Cm' : '', 'Bk' : '?',  'Ra' : '_sv', 'Fr' : '_sv'}
    potdir = '$VSC_DATA_VO/shared/potcars/old_potpaw_PBE'
elif args.set == 'kurt':
    potentials =  {'H':'_h_GW','He':'_GW','Li':'_sv_GW', 'Be':'_sv_GW', 'B':'_GW', 'C':'_GW', 'N':'_h_GW', 'O':'_h_GW', 'F':'_h_GW', 'Ne':'_GW', 'Na':'_sv_GW', 'Mg':'_sv_GW',
                'Al':'_GW', 'Si':'_GW', 'P':'_GW', 'S':'_GW', 'Cl':'_GW', 'Ar':'_GW', 'K':'_sv_GW', 'Ca':'_sv_GW', 'Sc':'_sv_GW', 'Ti':'_sv_GW', 'V':'_sv_GW',
                'Cr':'_sv_GW', 'Mn':'_sv_GW', 'Fe':'_sv_GW', 'Co':'_sv_GW', 'Ni':'_sv_GW', 'Cu':'_sv_GW', 'Zn':'_sv_GW', 'Ga':'_d_GW', 'Ge':'_d_GW', 'As':'_GW', 'Se':'_GW',
                'Br':'_GW', 'Kr':'_GW', 'Rb':'_sv_GW', 'Sr':'_sv_GW', 'Y':'_sv_GW', 'Zr':'_sv_GW', 'Nb':'_sv_GW', 'Mo':'_sv_GW', 'Tc':'_sv_GW', 'Ru':'_sv_GW',
                'Rh':'_sv_GW', 'Pd':'_sv_GW', 'Ag':'_sv_GW', 'Cd':'_sv_GW', 'In':'_d_GW', 'Sn':'_d_GW', 'Sb':'_d_GW', 'Te':'_GW', 'I':'_GW', 'Xe':'_GW', 'Cs':'_sv_GW',
                'Ba':'_sv_GW', 'La':'_GW',
                'Lu':'_3', 'Hf':'_sv_GW', 'Ta':'_sv_GW', 'W':'_sv_GW', 'Re':'_sv_GW', 'Os':'_sv_GW', 'Ir':'_sv_GW', 'Pt':'_sv_GW', 'Au':'_sv_GW',
                'Hg':'_sv_GW', 'Tl':'_d_GW', 'Pb':'_d_GW', 'Bi':'_d_GW', 'Po':'_d_GW', 'At':'_d_GW','Rn':'_d_GW', 'Ac' : '', 'Am' : '', 'Ce' : '_GW', 'Dy' : '_3', 'Er' : '_3' , 'Eu' : '_2',
                'Gd' : '_3', 'Ho' : '_3', 'Nd' : '_3', 'Np' : '', 'Pa' : '', 'Pm' : '_3', 'Pr' : '_3', 'Pu' : '', 'Ra' : '_sv', 'Sm' : '_3', 'Tb' : '_3', 'Th' : '', 'Tm' : '_3', 'U' : '', 'Yb' : '_2'}
    potdir = '$VSC_DATA_VO/shared/potcars/potpaw_PBE.54'
elif args.set == 'kurtnohard':
    potentials =  {'H':'_GW','He':'_GW','Li':'_sv_GW', 'Be':'_sv_GW', 'B':'_GW', 'C':'_GW', 'N':'_GW', 'O':'_GW', 'F':'_GW', 'Ne':'_GW', 'Na':'_sv_GW', 'Mg':'_sv_GW',
                'Al':'_GW', 'Si':'_GW', 'P':'_GW', 'S':'_GW', 'Cl':'_GW', 'Ar':'_GW', 'K':'_sv_GW', 'Ca':'_sv_GW', 'Sc':'_sv_GW', 'Ti':'_sv_GW', 'V':'_sv_GW',
                'Cr':'_sv_GW', 'Mn':'_sv_GW', 'Fe':'_sv_GW', 'Co':'_sv_GW', 'Ni':'_sv_GW', 'Cu':'_sv_GW', 'Zn':'_sv_GW', 'Ga':'_d_GW', 'Ge':'_d_GW', 'As':'_GW', 'Se':'_GW',
                'Br':'_GW', 'Kr':'_GW', 'Rb':'_sv_GW', 'Sr':'_sv_GW', 'Y':'_sv_GW', 'Zr':'_sv_GW', 'Nb':'_sv_GW', 'Mo':'_sv_GW', 'Tc':'_sv_GW', 'Ru':'_sv_GW',
                'Rh':'_sv_GW', 'Pd':'_sv_GW', 'Ag':'_sv_GW', 'Cd':'_sv_GW', 'In':'_d_GW', 'Sn':'_d_GW', 'Sb':'_d_GW', 'Te':'_GW', 'I':'_GW', 'Xe':'_GW', 'Cs':'_sv_GW',
                'Ba':'_sv_GW', 'La':'_GW',
                'Lu':'_3', 'Hf':'_sv_GW', 'Ta':'_sv_GW', 'W':'_sv_GW', 'Re':'_sv_GW', 'Os':'_sv_GW', 'Ir':'_sv_GW', 'Pt':'_sv_GW', 'Au':'_sv_GW',
                'Hg':'_sv_GW', 'Tl':'_d_GW', 'Pb':'_d_GW', 'Bi':'_d_GW', 'Po':'_d_GW', 'At':'_d_GW','Rn':'_d_GW', 'Ac' : '', 'Am' : '', 'Ce' : '_GW', 'Dy' : '_3', 'Er' : '_3' , 'Eu' : '_2',
                'Gd' : '_3', 'Ho' : '_3', 'Nd' : '_3', 'Np' : '', 'Pa' : '', 'Pm' : '_3', 'Pr' : '_3', 'Pu' : '', 'Ra' : '_sv', 'Sm' : '_3', 'Tb' : '_3', 'Th' : '', 'Tm' : '_3', 'U' : '', 'Yb' : '_2'}
    potdir = '$VSC_DATA_VO/shared/potcars/potpaw_PBE.54'
f = open('POTCAR','w')
f.close()
for i in range(0,len(args.els)):
    subprocess.call('cat ' + potdir + '/' + args.els[i] + potentials[args.els[i]] + '/POTCAR  >> POTCAR', shell=True)


